bibl and ref tags testing
NewcastleRSE/beeing-human-tei-data pull request #25
Opened 2023-10-03 16:54 UTC by OliviaFS

## Description

I tried adding a few bibl refs, and also the targets. I think I got them wrong, could you check please. I also forgot to update the list of changes at the start of the document! Perhaps you could consider this a test of the process and then just delete the branch and I will start again. 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Manually

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

Just a bit of initial feedback and help.

2023-10-04 08:09 UTC, tiagosousagarcia commented
@OliviaFS, do you mean for me to review this? You need to add me as a reviewer, otherwise I don't get any notifications

2023-10-04 08:46 UTC, tiagosousagarcia requested changes
Looking good, just a couple of things to note. Later, I can just do these minute corrections myself, but I think at the start it would be better for you to do them, to get used to the process. I'll divide them by line numbers, which should be the same for you and make it easier to find:

**l. 6572**
I think there are two references in this note, so you need two `<ref>` -- the way I read it, Butler is pointing to the whole of chapter 6 and to note 24 in chapter 7, so this is how I would encode it:
```
<ref target="#ch6">V.6.</ref><ref target="#ch7sumn24">7.n.24.</ref>
```
targets must also **always** start with `#`, and the notes that he points to are **always** 'summary' (no other notes are numbered).

***

**l. 7476**
You are missing the `#` at the start of the target, and chapter 10 is the only one that has slightly different ids: you need to indicate the part after the chapter, so it becomes:
```
<ref target="#ch10p1sumn15">V.c.10.p.1.n.15</ref>
```

***

**l. 8176**
It is a bibliographic note pointing towards a summary note, so the code in the `target` should be a `sum`:
```
<ref target="#ch7sumn46">V.c.7.n.46</ref>
```

***

**l. 8715**
Again, I think he points to two different notes here (27 and 28), so you need two `<ref>`. You are also missing the `#` at the start of the target, and the note it points to is a summary note, so this should be:
```
<ref target="#ch6sumn27">V.c.6.n.27</ref>&amp;<ref target="#ch6sumn28">28</ref>
```

***

To correct these, simply make the changes on your copy, save commit and push. I can have another look then if you wish, otherwise keep making the corrections and I'll look at them once you are ready to merge the branch. 

You won't need to create a new pull request now, just keep using this one and let me know once we're ready for the final review and merge.

2023-10-06 09:55 UTC, OliviaFS commented on 1623.xml
> +                        ><ref target="#ch4bibln20">v.c.4.n.20</ref></note> which is a signe that the first <fw type="catch">
I can see this one at 4734 should be sumn not bibln sorry

2023-10-06 10:07 UTC, OliviaFS commented
Has this updates with my new changes? @tiagosousagarcia

2023-10-06 13:47 UTC, OliviaFS commented on 1623.xml
@tiagosousagarcia I've done perhaps half of these. Could you check I'm doing them correctly? I am not sure what to do with the refs for the markers (eg V. or *) that lead to the references. Should I give them the same xml-id as the longer marginal reference they're linked to, so that the in-text V. and the marginal V.c.6.n.5 both point to xml-id #ch6sumn5? Thanks!

2023-10-09 07:51 UTC, tiagosousagarcia commented on 1623.xml
So, I think the 'v.' in the body of the text should point towards the side note, and then the side note should point to the body of the text, like so:

```
 When you would have no more swarmes, as namely after the first blowing of Blackberries, <ref target="#ch3bibln23">v:</ref>
<note type="authorial" subtype="bibliographic" xml:id="ch3bibln23">
    <ref target="#ch5sumn11"> V.c.5.n11.</ref>
</note> which is commonly within a seven night after Midsummer
```

2023-10-09 08:01 UTC, tiagosousagarcia approved these changes
That all looks good, can't see anything wrong. Just add the missing note to line 5029 (and remove the editorial note that says missing) if you know what it is, but otherwise it is ready to merge. Then open a new branch for the rest of the refs, remember to keep things compartmentalised.

2023-10-09 09:55 UTC, OliviaFS commented
Hello, just finishing off the refs. As in line 3819 where I've split a ref into two, as two places are mentioned in the margin under one note, is it ok that there isn't a new xml id for the second (new) half? So that essentially the "v" points only to the first half? Thanks

2023-10-09 10:04 UTC, tiagosousagarcia commented
> Hello, just finishing off the refs. As in line 3819 where I've split a ref into two, as two places are mentioned in the margin under one note, is it ok that there isn't a new xml id for the second (new) half? So that essentially the "v" points only to the first half? Thanks

The 'v' should point to the `note` element that contains the `ref`, not to the `ref` itself -- so the note contains both refs. Does that make sense?

2023-10-09 10:10 UTC, tiagosousagarcia commented
So here's the example @OliviaFS:

```
leave to play, <ref target="#ch3bibln35">v.</ref>
                    <note type="authorial" subtype="bibliographic" xml:id="ch3bibln35">
                        <ref target="#ch3sumn59"> V.n. 59</ref>.&amp;<ref target="#ch1sumn59">c.1.n.59.</ref>
                    </note> and to refresh
```
Notice that the `target` for the 'v.' is the `xml:id` for the `note`, not the `ref`, and that the `note` element contains both references to the other bits of text. So the v. points to the entire side note, not a specific one. Is this helpful?

2023-10-09 10:37 UTC, merged