Variation ch3
NewcastleRSE/beeing-human-tei-data pull request #74
Opened 2024-02-16 11:00 UTC by OliviaFS

## Description

To publish a preview of ch3 variation so I can have a second pass at it. 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Manually 

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

Coding errors

2024-02-26 11:56 UTC, tiagosousagarcia reviewed
Great work on this chapter, I'm surprised you haven't gone entirely mad yet! I've made a couple of direct corrections, and there's only three bits that I would like you to have another look at. If you're struggling, let me know and I'll have a closer look at the collation myself as well.

- #ch3p44 - #ch3p48 -- this is quite a complex section, could you have another look? There's a couple of things I think might need attention.  For example, in the app around the note that starts '*The length may be three inches and...', you have a `rdg` that points to an entire paragraph in 1609, though I think there is a case to be made that this could be considered new text; similarly, you marked paragraph 45 as being a change from another paragraph in 1609, but it might be worth considering whether the changes are strong enough to be considered additions and deletions. In essence, there's something that it's not quite right with the encoding of this section, but I can't quite put my finger on it just yet, so could you have another look at it again?
- ch3par70 -- there are three changes that all point to the same anchors, ch3ancs54 -- can you double check that?
- ch3par73 -- two changes pointing to the same anchors, ch3ancs57 -- can you double check that?

2024-02-28 10:11 UTC, OliviaFS commented
Hello, 
I intentionally did the apps pointing to the same anchors, on the grounds that they're only separate anchors because the formatting in 1623 prevents them from being one big anchor. Usually I've done this when the anchors should (in the absence of <p>) be one long major change. Does it not work? I can change it if so. I just thought they could all lead to the same big patch of 1609, even though they are by neccessity chunked up into smaller bits. 
I'll check the other section now.

2024-02-28 10:17 UTC, tiagosousagarcia commented
I see, I thought that might be the case. It makes perfect sense, but I need to think whether there's a better solution for that kind of thing. I'm at the music thing today, so might not have the time until next week

2024-02-28 10:22 UTC, OliviaFS commented
Of course, no probs. Say hi to everyone for me, I wish I was there too. Olivia On 28 Feb 2024, at 10:17, tiagosousagarcia ***@***.***> wrote:﻿
I see, I thought that might be the case. It makes perfect sense, but I need to think whether there's a better solution for that kind of thing. I'm at the music thing today, so might not have the time until next week

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-28 10:24 UTC, OliviaFS commented
Also I have in other places chunked the anchors up to make them more match the apps. Let's think about it.

2024-02-28 11:24 UTC, OliviaFS commented
Also if you see Jenny in person do update her (I have over email too)

2024-03-20 11:22 UTC, tiagosousagarcia requested changes
I'm afraid you're not rid of chapter 3 just yet. It is better, but there is still work to do. I've indicated some specific points below, but first you need to review how you are using the `transpose` element. There are three things wrong with what you are doing:

1. There should only be _one_ `listTranspose` element in the entire document, and that should be inside a `standOff`; that `standOff` element is not inside the `text` but between `teiHeader` and `text`; every time you identify a transposition, you create a new `transpose` element not where it happens but inside the `listTranspose` (which, again, is inside the `standOff` element which is itself outside `text`); the witness for `listTranspose` should be `#b1609` (i.e., where the differently ordered text is found);
2. You _cannot_ create new paragraphs in 1623, you use the ids of the paragraphs that exist there. There shouldn't be any Ap1 or Bp1 -- those were example ids from the documentation. Let's say the first two paragraphs of chapter 3 where switched from 1609, this is what the `transpose` element should look like:
```
<transpose>
  <ptr target="#ch3par2"/>
  <ptr target="#ch3par1"/>
</transpose>
```
i.e., in 1609 what is 'ch3par2' in 1623 appears _before_ what is 'ch3par1' in 1623. If the transposed sections are smaller than paragraphs, you use the element `<seg>` to mark them up, and give them an id in the format `chXsegY` as in:
```
<p id="ch3par1">This is the start of the chapter. <seg xml:id="ch3seg1">This is one section of the chapter.</seg> <seg xml:id="ch3seg2">This is another section of the chapter.</seg> This is the end of the chapter.</p>
```
You would then mark this transposition like so:
```
<transpose>
  <ptr target="#ch3seg2"/>
  <ptr target="#ch3seg1"/>
</transpose>
```
Which would mean the text in 1609 was:
```
This is the start of the chapter. This is another section of the chapter. This is one section of the chapter. This is the end of the chapter.
```
3. Once you identified a paragraph or section as a transposition, you should treat any variation inside of it as if they appear in the same spot and not try to encode the transposition using `app`. Let's say you have these two texts:

1623
```
<p xml:id="par1">This the paragraph about bees.</p>

<p xml:id="par2">This is the paragraph about the enemies.</p>
```

1609
```
This is the paragraph about the mice.

This is the paragraph about the bees.
```

The first thing to note is that the paragraphs are transposed in 1623, so you would create a `transpose` like so:
```
<transpose>
  <ptr target="#par2"/>
  <ptr target="#par1"/>
</transpose>
```
i.e., the paragraph about mice (or enemies) appears before the paragraph about bees in 1609. But once that transposition is marked, there's also difference inside the paragraphs, so you'd mark them like so:

1623
```
<p xml:id="par1">This the paragraph about
  <app type="minor" subtype="del">
    <lem wit="#b1623"/>
    <rdg wit="b1609">
      <ptr target="1609.xml#ancs1 1609.xml#ance1 "/>
    </rdg>
  </app> bees.
</p>

<p xml:id="par2">This is the paragraph about the 
   <app type="minor" subtype="change">
     <lem wit="#b1623">enemies</lem>
     <rdg wit="#b1609">
       <ptr target="1609.xml#ancs2 1609.xml#ance2"
     </rdg>
   </app>.
 </p>
```

1609
```
This is the paragraph about the <anchor xml:id="ancs2"/>mice<anchor xml:id="ance2"/>.

This is the paragraph about <anchor xml:id="ancs1"/>the<anchor xml:id="ance1"/> bees.
```
You might need to re-read [the documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/NewcastleRSE/beeing-human-tei-data/Variation-ch3/documentation/tei_beeing_human.html#encVarMov) carefully and let me know if there's something that's not clear.

Other things:

- ll. 3985-4000 [note id=ch3glon6] -- It should only be one `app` rather than two;
- ll. 4264 ff [paragraph id=ch3par43] -- Review the variation here: I think the start of the paragraph ('The use of the Winter-doore is to straighten the passage when there needeth not so much roome,') should precede the two deletions from 1609; also review the positions of the anchors in 1609 (ch3ancs32, ch3ance32, ch3ancs33, ch3ance33): i.e.: it is either one big deletion from ch3ancs32 until ch3ance33 where the change starts, or you have one deletion per 1609 paragraph; both are valid, but for processing and ease of reading, the second option is preferred. Breaking the `app` because there is a page break in 1609 as you have here is also technically valid, but makes the least sense to me; You also repeat one of those same deletions from 1609 after 'that the Bees may the better keepe out the Robbers,'. I think some of these problems come from corrections, but the more you do it, the harder it is to understand what is going wrong; I would recommend you clean this section of all `app` in 1623 and all anchors in 1609 and do it again from a clean text, otherwise you will spend more time tracking anchors than comparing texts.
- [1609] l. 2912 -- anchor ch3ance42xx should be just outside the `note`, not inside it.
- [1609] l. 2930 -- anchor ch3ance44x should be just outside the `hi`, not inside it. Also, you need to be consistent in how you mark these: in the case above, the anchors contained the note itself, not just their content;
- ll. 4654 ff [paragraph id=ch3par65] -- there are problems here caused by (I think) how you've used transpose (see above) -- correct those problems first, then redo the comparison.
- ll. 5025 -- typo: 'nd having thus' should be 'And having thus'

2025-04-03 09:05 UTC, tiagosousagarcia commented
this branch will be dead; replaced by NEW-ch3-variation that includes latest changes to the rest of the document

2025-04-03 09:05 UTC, closed without merging